import { config } from 'dotenv';
config();

import '@/ai/flows/summarize-code-snippet.ts';
import '@/ai/flows/generate-code-from-prompt.ts';
import '@/ai/flows/code-refactoring-suggestions.ts';
import '@/ai/flows/find-codebase-examples.ts';
import '@/ai/flows/enhanced-code-generation.ts';
import '@/ai/tools/file-system-operations.ts';
import '@/ai/tools/file-system-tree-generator.ts';
import '@/ai/tools/codebase-search.ts';
import '@/ai/tools/error-validation.ts';
import '@/ai/tools/code-usage-analysis.ts';
import '@/ai/tools/operation-progress.ts';
import '@/ai/tools/terminal-operations.ts';
import '@/ai/tools/file-system-executor.ts';
import '@/ai/tools/codebase-dataset.ts';
import '@/ai/tools/codebase-indexer.ts';
import '@/ai/tools/filename-suggester.ts';
import '@/ai/tools/smart-content-insertion.ts';
import '@/ai/tools/intelligent-code-merger.ts';
import '@/ai/tools/file-context-analyzer.ts';
import '@/ai/tools/smart-folder-operations.ts';
import '@/ai/tools/advanced-rag-system.ts';